
CREATE TABLE IF NOT EXISTS `nn_publish`(
    `id` INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,

    `name` VARCHAR(32) NOT NULL DEFAULT '',
    `city` VARCHAR(32) NOT NULL DEFAULT '',
    `email` VARCHAR(64) NOT NULL DEFAULT ''
);



ALTER TABLE `nn_publish` ADD COLUMN `operator_id` INT NOT NULL DEFAULT -1;